server:
  port: 8070

stock:
  token: ZZs434387wMHPVA5z3UxhSDMqy9fuuCsTxS438lt
  url:
    stock: https://api.stockdata.org/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: account
    password: account
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-dnqy-t57.eu.auth0.com/
  application:
    name: stock-service

security:
  jwt:
    expiration: 600
    secret: Vm10YWIyTXhXa2RqUm1oVlltMTRhRll3V2t0VVZtUnpZVWhLVVZWVU1Eaz0=

auth:
  audience: stock-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka