server:
  port: 8890

service:
  currency:
    uri: lb://CURRENCY-SERVICE
    path:
      all-exchange: /latest
      convert: /convert
    audience: currency-service
  stock:
    uri: lb://STOCK-SERVICE
    path:
      quoteByTickers: getQuoteByTickers
      endOfDayMultiple: getEndOfDayMultiple
    audience: stock-service

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            provider: auth0
            client-id: jhYUBYYBIJKINBYyguygd787asdbbjk
            client-secret: jkdsfkj98*(ihjfkkII(UHdnbkklcjhvsd8ufh99o43nnklH*(Y`kijkfoijm
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-dnqy-t57.eu.auth0.com/
      resourceserver:
        jwt:
          issuer-uri: https://dev-dnqy-t57.eu.auth0.com/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka