spring:
  thymeleaf:
    prefix: classpath:/views/
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: account
    password: account
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
logging:
  level:
    org.springframework: error
    org.springframework.boot: info
    io.app: trace
  file:
    path: log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{52} - %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{52} - %msg%n'

apps:
  base-url:
    currency: http://localhost:8090/currency